// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlxwuyeiuvfazesxwqny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhseHd1eWVpdXZmYXplc3h3cW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MTcyNzAsImV4cCI6MjA2NjM5MzI3MH0.EdBpWeHnvgmgez7ufPyYoVC8uSA_s-mRSAhmJUJYck4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);